name: crowdin
on:
  push:
    branches:
      - master
jobs:
  upload-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install crowdin-cli
        run: |
          wget https://github.com/crowdin/crowdin-cli/releases/download/3.2.1/crowdin-cli.zip
          echo "953e8714ca114b21eabd8f588d4b1c9e8ac1d1df3621176fc08ce611200f3108  crowdin-cli.zip" | sha256sum -c
          unzip crowdin-cli.zip -d crowdin-cli
      - name: Upload to Crowdin
        env:
          CROWDIN_SETTINGS: "${{ secrets.CROWDIN_SETTINGS }}"
        run: |
          echo "$CROWDIN_SETTINGS" > ~/.crowdin.yml
          java -jar ./crowdin-cli/3.2.1/crowdin-cli.jar push -c ~/.crowdin.yml -b master
